routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|


*/
//public routes
Route::get('add-more-time/{id}','ProductController@more_time');
Route::post('add-more-time','ProductController@add_more_time');

Route::get('/is_notified', 'ProductController@is_notified');
Route::get('countries-ajax','CityUserController@countries');
Route::get('cities-ajax/{id}','CityUserController@cities');
Route::get('category/{category_id}','CategoryController@getProductsByCategory');
Route::post('get-messages/{id}','HomeController@get_messages');
Route::post('send-messages','HomeController@send_message');

Route::get('country-ajax','CityUserController@country_ajax');

Route::get('get-dispatch-info/{id}','admin\DispatchController@get_info');

Route::resource('/reputation','ProfileController');

Route::get('/ver','ProductController@ver');

Route::get('set-com',function(){

$cities=App\City::all();

foreach ($cities as $key => $value) 
{
	$com=App\Community::create([
		"name"=>$value->name,
		"description"=>$value->name." community",
		"status"=>1,
		"public"=>1,
		"created_by"=>1,
		"city_id"=>$value->id
	]);

	$com->communityUsers()->attach(1,['is_approve'=>1]);

	if (count($value->products)) 
	{

		foreach ($value->products as $key => $p) 
		{
			$com->communityProducts()->attach($p->id);

		}

	}
}

return "success";

});

Route::get('json',function(){
$path = storage_path() . "/app/public/tapa.json"; // ie: /var/www/laravel/app/storage/json/filename.json

$json = json_decode(file_get_contents($path), true); 
$data=[];
$i=0;
foreach ($json as $key => $value) {

	#return $value;
	//titles
	$value["title"]=str_replace(['  '],'',$value["title"]);
	$value["title"]=preg_replace("/[\n\r\t]/","",$value["title"]);

	//description
	$arr_desc=array('\\"','<ul>','</ul>','<li>','</li>','<br>','<strong>','</strong>','<strike>','</strike>','<noscript>','</noscript>','<div>','</div>','<p>','</p>','<b>','</b>','<i>','</i>','<em>','</em>','<blockquote>','</blockquote>');

	$value["product_description"]=str_replace($arr_desc,'', $value["product_description"]);
	
	$value["product_description"] = preg_replace("/[\n\r\t]/","",$value["product_description"]); 
	$value["product_price"] = preg_replace("/[\n\r\t]/","",$value["product_price"]); 


	$data[$i]["title"]=$value["title"];
	$data[$i]["product_description"]=$value["product_description"];


	//if is base64

	#$contains=str_contains('base64',$value["product_image"]);

		//return strlen($value["product_image"]);

	$url=preg_match_all('#\bhttps?://[^,\s()<>]+(?:\([\w\d]+\)|([^,[:punct:]\s]|/))#',$value["product_image"], $match);

	$data[$i]["match"]=$match;

	$count=count($match[0]);

	if ($count>1) 
	{
		$cleaned=strstr($match[0][0], '"', true);

		if ($cleaned==false) 
		{
			$cleaned=$match[0][0].'.jpg';
		}

	}elseif($count==1){

		$cleaned=strstr($match[0][0], '"', true);
		if ($cleaned==false) 
		{
			$cleaned=$match[0][0].'.jpg';
		}

	}else
	{

		$cleaned=null;
	}


	#$data[$i]["match"]=$cleaned;
	$img='hard_cover_'.rand().'.jpg';
	$base='img/thumbnail/'.$img;
	$data[$i]["product_image"]=$img;
	
	$ch = curl_init($cleaned);
	$fp = fopen(public_path($base), 'wb');
	curl_setopt($ch, CURLOPT_FILE, $fp);
	curl_setopt($ch, CURLOPT_HEADER, 0);
	curl_exec($ch);
	curl_close($ch);
	fclose($fp);
	
	$value["product_price"]=str_replace(['desde',' ','US$'],'',$value["product_price"]);
	$data[$i]["product_price"]=$value["product_price"];



	$value["product_author"]=str_replace(['Visita la página de Amazon'],'',$value["product_author"]);
	$data[$i]["product_author"]=$value["product_author"];


	$i++;
}




foreach ($data as $key => $value) 
{
	$c=count($value["product_description"]);
	if ($c<1) 
	{
		$value["product_description"][0]=null;
	}

	$product= App\Product::create([
		"product_name"=>$value["title"],
		"product_desc"=>$value["product_description"][0],
		"price"=>$value["product_price"],
		"product_img"=>$value["product_image"],
		"author"=>$value["product_author"],
		"product_category"=>10,
		"is_active"=>1,
		"in_front"=>1,
		"city_id"=>5167,
		"user_id"=>1,
		"share_all"=>1,
		"country_id"=>44,
		"is_premium"=>1
	]);

	$p2=App\ProductImage::create([
		"photo"=>$product->product_img,
		"product_id"=>$product->id
	]);

}
return "success";

});

Route::resource('products', 'ProductController', ['names' => [
	'create' => 'createproduct',
	'index' => 'product',
	'show' => 'productdetail',
	'store' => 'addproduct',
	'destroy' => 'deleteproduct',

]]);
//Route::get('demos/jquery-image-upload','CommunityController@showJqueryImageUpload');

Route::group(['prefix' => 'admin', 'namespace' => 'admin', 'middleware' => ['auth','admin','web']], function () {
// Inicio

	Route::get('/', function () {
		$titulo = "Inicio";
		return view('admin.index', compact("titulo"));
	});



	/*Despacho*/
	Route::resource('/shipping-records','DispatchController');

	/*Feedback*/
	Route::resource('/feedback', 'FeedBackController');

	#solicitudes
	Route::resource('/borrows', 'BorrowController');
	Route::get('/borrows-status/{id}', 'BorrowController@status');

	/*Estadisticas*/
	Route::resource('/estadisticas', 'EstadisticaController');
	Route::get('estadisticas-date','EstadisticaController@date');
	/* Usuarios */
	Route::resource('/users', 'UserController');
	Route::post('users/role-admin/{id}','UserController@addRole');

	Route::post('/updateUser/{user_id}', 'UserController@updateUser')->name('updateUser');
	/* Categorias */
	Route::resource('/categories', 'CategoryController');
// actualizar categoria
	Route::post('/updateCategory/{category_id}', 'CategoryController@updateCategory')->name('updateCategory');
	/* Ciudades */
	Route::resource('/cities', 'CityController');
// editar ciudad
	Route::post('/updateCity/{city_id}', 'CityController@updateCity')->name('updateCity');
// deshabilitar ciudad
	Route::get('/disabledCities', 'CityController@disabledCities')->name('disabledCities');
	/* Productos (administrador) */
	Route::resource('/products', 'ProductAdminController');
	Route::post('products/delete_multi', 'ProductAdminController@delete_multi');

// editar producto
	Route::post('/updateProduct/{product_id}', 'ProductAdminController@updateProduct')->name('updateProduct');
// productos "premium"
	Route::get('/premiumProducts', 'ProductAdminController@premiumProducts')->name('premiumProducts');
// productos en Exhibicion
	Route::get('/displayedProducts', 'ProductAdminController@displayedProducts')->name('displayedProducts');
//productos prestados
	Route::get('/borrowedProducts', 'ProductAdminController@borrowedProducts')->name('borrowedProducts');

// productos sin Exhibir
	Route::get('/undisplayedProducts', 'ProductAdminController@undisplayedProducts')->name('undisplayedProducts');
	/* Comunidades */
	Route::resource('/communities', 'CommunityController');
// actualizar comunidad
	Route::post('/community/{community_id}/updateCommunity', 'CommunityController@updateCommunity')->name('updateCommunity');
// Comunidades inactivas
	Route::get('inactiveCommunities', 'CommunityController@inactiveCommunities')->name('inactiveCommunities');
	/* Planes de Tarifas (Membresias) */
	Route::resource('/fees', 'FeesController');
// actualizar plan de tarifa
	Route::post('/updateRates/{fee_id}', 'FeesController@updateRates')->name('updateRates');
	/* Config */
	Route::group(['prefix' => 'config', 'namespace' => 'Config'], function () {
// editar datos de usuario logueado
		Route::post('user/{user_id}/editData', 'UsuarioController@editUser')->name('editUser');
		Route::resource('/', 'ConfigController')->only([
			'index', 'store'
		]);
		Route::put('/usuariosSide','UsuarioController@usuariosSide');
		Route::resource('/usuarios', 'UsuarioController');
		Route::put('/cambiarFoto/{user_id}', 'UsuarioController@cambiarFoto');
		Route::group(['prefix' => 'privilegios', 'namespace' => 'Privilegios'], function () {
			Route::resource('/roles', 'RolesController');
			Route::resource('/permisos', 'PermissionsController');
		});
	});
});
//delete order
Route::post('deleteOrder','ProductController@deleteOrder');
Route::post('returnedOrder/{id}','ProductController@returnedOrder');
Route::post('received-order/{id}','ProductController@receivedOrder');


Route::resource('/plans','PlanController');
Route::get('/subscription/create', 'SubscriptionController@create');
Route::get('/subscription/init', 'SubscriptionController@pay');
Route::get('/subscription/card_inscription_return', 'SubscriptionController@cardInscriptionReturn');
Route::get('/subscription/success/{subscription_id}', 'SubscriptionController@success');
//pago
Route::post('/charge/pay', 'ChargeController@pay');
Route::get('/charge/return_after_form', 'ChargeController@returnAfterForm');
//search communities
Route::get('/search-communities','CommunityController@filter_communities');
Route::get('/search-communities/name','CommunityController@filter_communities_by_name');
//search categories
Route::get('/search-name','CategoryController@getProductsByName');
Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'HomeController@switchLang']);
Route::get('/user/products/{id}','ProductController@getusersproducts');
Route::post('/demos/jquery-image-upload/{id}/{image}','CommunityController@saveJqueryImageUpload');
Route::get('/', "HomeController@index")->name('home');
Route::get('/logout', ['as' => 'logout', 'uses' => 'HomeController@logout']);
// Añadir Nueva Ciudad
Route::post('/addcity', "HomeController@addCity");
Route::get('/cityproduct/{id}','ProductController@cityproduct');
Route::get('/categoryproduct/{id}','ProductController@categoryproduct');
Route::get('/category-filter','CategoryController@categoryByFilter');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
        protected $table = 'categories';
        
        protected $fillable=[
        	"name",
        	"name_spanish",
        	"is_active"
        ];

}

app/Http/Controllers/admin/CategoryController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\View;
use App\Category;

class CategoryController extends Controller
{
      /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

     public function __construct() {
      
        /*
        $this->middleware("permission:garantias_ver");
        $this->middleware("permission:garantias_crear")->only("create", "store");
        $this->middleware("permission:garantias_editar")->only("edit", "update");
        $this->middleware("permission:garantias_eliminar")->only("destroy");
       */
        View::share('titulo', "Categorias");
    }

    public function index(Request $request)
    {
        if ($request->ajax()) 
        {
            $categories = Category::all();
            return response()->json($categories);
        }

        return view('admin.categories.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
             'name_spanish' => 'required | unique:categories',
            'name' => 'required | unique:categories',
            'price'=>'required'
        ]);

        $save = Category::create([
            "name_spanish" => strtolower($request->name_spanish),
            "name" => strtolower($request->name),
            "price"=>$request->required 
        ]);

        if ($save == true){
            return response()->json(["success" => true]);
        } else{
            return response()->json(["success" => false]);
        }
    }

    //Habilitar / Deshabilitar Categoria
    public function enableCategory($id)
    {
        $category = Category::find($id);

        if($category->is_active === 1){
            $category->update([ 'is_active' => 0 ]);
            return response()->json([
                'message' => 'Categoria deshabilitada!'
            ]);
        }else{
            $category->update([ 'is_active' => 1 ]);
            return response()->json([
                'message' => 'Categoria habilitada!'
            ]);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        return view('admin.categories.edit',compact('category'));
    }

    // actualizar categoria
    public function updateCategory(Request $request, $id)
    {
         $this->validate($request, [
            'name' => 'required',
            'name_spanish' => 'required',
            'price'=>'required'
        ]);

         $category = Category::find($id);
         $category->name = $request->name;
         $category->name_spanish = $request->name_spanish;
         $category->price=$request->price;
         $update = $category->save();

         if ($update) 
        {
            return response()->json(["success" => true]);
        }else{
            return response()->json(["success" => false]);

        }
    }    

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::destroy($id);

       return response()->json([
            "success" => true,
            "message" => "Categoria Eliminada!"
        ]);

    }
}

resources/views/admin/categories/create.blade.php
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="text-center modal-title">
                Nueva Categoria
            </h4>
        </div>

            <div class="modal-body">
                <form id="createCategoryForm" action="{{ route('categories.store') }}" method="POST" enctype="multipart/form-data" autocomplete="off">

                    {{ csrf_field() }}

                    <div class=" row text-center">

                         <div class=" my-1 col-6">
                            <div class="form-group">
                            {!! Form::label('name', 'Nombre (Español):') !!}
                                <input type="text" class="form-control" name="name_spanish"  style="width: 70%; margin: 0 auto;" placeholder="Categoria">
                            </div> 

                            <div class="form-group">
                            {!! Form::label('name', 'Nombre ingles:') !!}
                                <input type="text" class="form-control" name="name"  style="width: 70%; margin: 0 auto;" placeholder="Categoria">
                            </div>

                                <div class="form-group">
                            {!! Form::label('price', 'Precio de Envio') !!}
                                <input type="text" class="form-control" style="width: 70%; margin: 0 auto;" name="price"  value="" placeholder="Precio">
                            </div>

                        </div>

                    </div>


                    <div class="modal-footer">
                        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">
                            Cerrar
                        </button>
                        <button type="submit" class="btn btn-primary" id="sendCreateCategoryForm">
                            Crear
                        </button>
                    </div>

                </form>
            </div>
        
        </div>
    </div>
</div>
@push('js')
    @include ('admin.categories.js.create')
@endpush

resources/views/admin/categories/edit.blade.php
<div class="modal-dialog" role="document">
    <div class="modal-content">

        <div class="modal-header">

            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>

            <h4 class="text-center modal-title">
                Editar Categoria
            </h4>

        </div>

            <div class="modal-body">
                <form id="updateCategoryForm" action="{{ route('updateCategory', ['id' => $category->id]) }}" method="POST" enctype="multipart/form-data" autocomplete="off">

                    {{ csrf_field() }}

                    <div class=" row text-center">

                        <div class=" my-1 col-6">
                            
                            <div class="form-group">
                            {!! Form::label('name', 'Nombre (Español):') !!}
                                <input type="text" class="form-control" style="width: 70%; margin: 0 auto;" name="name_spanish"  value="{{ $category->name_spanish }}">
                            </div>

                            <div class="form-group">
                            {!! Form::label('name', 'Nombre (Ingles):') !!}
                                <input type="text" class="form-control" style="width: 70%; margin: 0 auto;" name="name"  value="{{ $category->name }}">
                            </div>

                               <div class="form-group">
                            {!! Form::label('price', 'Precio De Envio') !!}
                                <input type="text" class="form-control" style="width: 70%; margin: 0 auto;" name="price"  value="{{ $category->price }}">
                            </div>

                        </div>

                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">
                            Cerrar
                        </button>
                        <button type="submit" class="btn btn-info" id="sendUpdateCategoryForm">
                            Salvar
                        </button>
                    </div>

                </form>
            </div>
        
        </div>
    </div>
</div>

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.layout')

@section('content')
    <div class="block full">

        <div class="block-title">
            <h2>Categorias</h2>
        </div>

        {{-- envia a metodo create --}}
       <div class="row">
            <div class="col-md-12 text-right">
                <a data-target='#createCategoryModal' data-toggle='modal' href="#" class="btn btn-info btn-effect-ripple"><i class="fa fa-plus"></i>
                 Nuevo
                </a>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <br/><br/>
                <div class="table-responsive">
                    <div class="dataTables_wrapper form-inline no-footer">
                        <div class="_tabla">
                            <table class="table responsive table-vcenter dataTable no-footer" id="_table" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th class="text-center">Nombre</th>
                                        <th class="text-center">Opciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>                        
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

                            {{-- crear categoria --}}
    <div class="modal fade" id="createCategoryModal" tabindex="-1" role="dialog" aria-labelledby="createCategoryModal" aria-hidden="true">
       @include('admin.categories.create')
    </div>

                                {{-- Ver Categoria --}}
    <div class="modal fade" id="editCategoryModal" tabindex="-1" role="dialog" aria-labelledby="editCategoryModal" aria-hidden="true">
    </div>

@endsection

@push('js')
    @include ('plugins.datepicker')
    @include ('plugins.datatable')
    @include('admin.categories.js.index')
    @include ('admin.categories.js.edit')


@endpush